env: "local" # local, dev, prod
postgres:
  dsn: "postgres://postgres:postgres@127.0.0.1:5432/TaskManagement?sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s